import { Dispatch } from "redux";
import { toast } from "react-toastify";

// Action Types
export const SUBDEPARTMENT_LOADING = "SUBDEPARTMENT_LOADING";
export const SUBDEPARTMENT_ERROR = "SUBDEPARTMENT_ERROR";
export const GET_SUBDEPARTMENTS_SUCCESS = "GET_SUBDEPARTMENTS_SUCCESS";
export const CREATE_SUBDEPARTMENT_SUCCESS = "CREATE_SUBDEPARTMENT_SUCCESS";
export const UPDATE_SUBDEPARTMENT_SUCCESS = "UPDATE_SUBDEPARTMENT_SUCCESS";
export const DELETE_SUBDEPARTMENT_SUCCESS = "DELETE_SUBDEPARTMENT_SUCCESS";
