// Action Types
export const SUBLOCATION_LOADING = "SUBLOCATION_LOADING";
export const SUBLOCATION_ERROR = "SUBLOCATION_ERROR";
export const GET_SUBLOCATIONS_SUCCESS = "GET_SUBLOCATIONS_SUCCESS";
export const CREATE_SUBLOCATION_SUCCESS = "CREATE_SUBLOCATION_SUCCESS";
export const UPDATE_SUBLOCATION_SUCCESS = "UPDATE_SUBLOCATION_SUCCESS";
export const DELETE_SUBLOCATION_SUCCESS = "DELETE_SUBLOCATION_SUCCESS";
