import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import connectDB from "@/backend/config/db";

import { Providers } from "./providers";

// DB connection + first-run bootstrap happen in src/instrumentation.ts (runs
// once on server startup). This keeps the request-time connection warm.
connectDB();

const inter = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Asset Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`} suppressHydrationWarning>
        <Providers>
          <ToastContainer
            position="top-right"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop
            closeOnClick
            pauseOnHover
            rtl={false}
            pauseOnFocusLoss
            draggable
          />
          {children}
        </Providers>
      </body>
    </html>
  );
}
