import { Dispatch } from "redux";
import { toast } from "react-toastify";

// Action Types
export const DEPARTMENT_LOADING = "DEPARTMENT_LOADING";
export const DEPARTMENT_ERROR = "DEPARTMENT_ERROR";
export const GET_DEPARTMENTS_SUCCESS = "GET_DEPARTMENTS_SUCCESS";
export const CREATE_DEPARTMENT_SUCCESS = "CREATE_DEPARTMENT_SUCCESS";
export const UPDATE_DEPARTMENT_SUCCESS = "UPDATE_DEPARTMENT_SUCCESS";
export const DELETE_DEPARTMENT_SUCCESS = "DELETE_DEPARTMENT_SUCCESS";
